/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://kksf3hvg4rcsflse5jeesqsmki.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qp6j4obhl5crvafpdrloce5mwy",
    "aws_cognito_identity_pool_id": "us-east-1:ecbde8b9-011d-4401-b638-7b4562133be0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_roxwEvlnG",
    "aws_user_pools_web_client_id": "5pphla1vk8umevte1p1mjnvc14",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "autopacksummitapp94b14feadba64f23aff0ed8deae77b99bc6-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
